config/routes.rb
Rails.application.routes.draw do
  get 'baixar' => 'application#baixar'
  get 'creditos' => 'application#creditos'
  get 'privacidade' => 'application#privacidade'
  get 'buscaavancada' => 'application#buscaavancada'
  get 'exportadores' => 'application#exportadores'
  get 'duvidas' => 'application#duvidas'

  root :to => "catalog#index"
  blacklight_for :catalog
  Blacklight::Marc.add_routes(self)
  devise_for :users

  get "/:id" => "catalog#show", :constraints => {:id => /[0-9]{4}\/[0-9]{2}\/[0-9]{2}\/[0-9]+/}

end

app/controllers/catalog_controller.rb
# -*- encoding : utf-8 -*-
#
class CatalogController < ApplicationController  
  include Blacklight::Marc::Catalog

  include Blacklight::Catalog

  configure_blacklight do |config|
    ## Default parameters to send to solr for all search-like requests. See also SolrHelper#solr_search_params
    config.default_solr_params = { 
      :qt => 'search',
      :rows => 10,
      :df => 'texto',
      :"hl" => true,
      :"hl.snippets" => 3,
      :"hl.fragsize" => 250
    }
    
    # solr path which will be added to solr base url before the other solr params.
    config.solr_path = 'select' 
    
    # items to show per page, each number in the array represent another option to choose from.
    config.per_page = [10,20,50,100]

    ## Default parameters to send on single-document requests to Solr. These settings are the Blackligt defaults (see SolrHelper#solr_doc_params) or 
    ## parameters included in the Blacklight-jetty document requestHandler.
    #
    config.default_document_solr_params = {
      :qt => 'document',
    #  ## These are hard-coded in the blacklight 'document' requestHandler
      :fl => '*',
      :rows => 1,
      :q => '{!raw f=id v=$id}'
    }

    # solr field configuration for search results/index views
    config.index.title_field = 'Diários Oficiais Da Cidade De São Paulo'
    config.index.display_type_field = 'format'

    # solr field configuration for document/show views
    config.show.title_field = 'Diários Oficiais Da Cidade De São Paulo'
    config.show.display_type_field = 'format'

    # solr fields that will be treated as facets by the blacklight application
    #   The ordering of the field names is the order of the display
    #
    # Setting a limit will trigger Blacklight's 'more' facet values link.
    # * If left unset, then all facet values returned by solr will be displayed.
    # * If set to an integer, then "f.somefield.facet.limit" will be added to
    # solr request, with actual solr request being +1 your configured limit --
    # you configure the number of items you actually want _displayed_ in a page.    
    # * If set to 'true', then no additional parameters will be sent to solr,
    # but any 'sniffed' request limit parameters will be used for paging, with
    # paging at requested limit -1. Can sniff from facet.limit or 
    # f.specific_field.facet.limit solr request params. This 'true' config
    # can be used if you set limits in :default_solr_params, or as defaults
    # on the solr side in the request handler itself. Request handler defaults
    # sniffing requires solr requests to be made with "echoParams=all", for
    # app code to actually have it echo'd back to see it.  
    #
    # :show may be set to false if you don't want the facet to be drawn in the 
    # facet bar
    config.add_facet_field 'secretaria_facet', :label => 'Secretaria', :limit => 10 
    config.add_facet_field 'orgao_facet', :label => 'Orgão', :limit => 10 
    config.add_facet_field 'tipo_conteudo_facet', :label => 'Tipo de Conteúdo', :limit => 10 
    #config.add_facet_field 'secretaria_facet', :label => 'Publication Year', :single => true
    #config.add_facet_field 'tipo_conteudo_facet', :label => 'Topic', :limit => 20 
    #config.add_facet_field 'language_facet', :label => 'Language', :limit => true 
    #config.add_facet_field 'lc_1letter_facet', :label => 'Call Number' 
    #config.add_facet_field 'subject_geo_facet', :label => 'Region' 
    #config.add_facet_field 'subject_era_facet', :label => 'Era'  

    #config.add_facet_field 'example_pivot_field', :label => 'Pivot Field', :pivot => ['format', 'language_facet']

    config.add_facet_field 'data', :label => 'Data de Publicação', :query => {
      :date_range => { :label => 'Intervalo de Datas', :fq => "data:[* TO *]" }, :week_1 => { :label => 'Menos de 1 semana', :fq => "data:[#{Date.today - 7.days}T00:00:00.000Z TO #{Date.today}T00:00:00.000Z]" },
      :month_1 => { :label => 'Menos de 1 mês', :fq => "data:[#{Date.today - 1.months}T00:00:00.000Z TO #{Date.today}T00:00:00.000Z]" },
      :years_1 => { :label => 'Menos de 1 ano', :fq => "data:[#{Date.today - 1.years}T00:00:00Z TO #{Date.today}T00:00:00.000Z]" },
      :years_5 => { :label => 'Menos de 5 anos', :fq => "data:[#{Date.today - 5.years}T00:00:00Z TO #{Date.today}T00:00:00.000Z]" },
      :years_mais_5 => { :label => 'Mais de 5 anos', :fq => "data:[* TO #{Date.today - 5.years}T00:00:00Z]" }
    }


    # Have BL send all facet field names to Solr, which has been the default
    # previously. Simply remove these lines if you'd rather use Solr request
    # handler defaults, or have no facets.
    config.add_facet_fields_to_solr_request!

    # solr fields to be displayed in the index (search results) view
    #   The ordering of the field names is the order of the display 
    config.add_index_field 'data', :label => 'Data'
    config.add_index_field 'secretaria', :label => 'Secretaria'
    config.add_index_field 'orgao', :label => 'Orgão'
    config.add_index_field 'tipo_conteudo', :label => 'Tipo de Conteúdo'
    config.add_index_field 'texto', :label => 'Texto', :highlight => true


    # solr fields to be displayed in the show (single result) view
    #   The ordering of the field names is the order of the display 
    config.add_show_field 'data', :label => 'Data'
    config.add_show_field 'secretaria', :label => 'Secretaria'
    config.add_show_field 'orgao', :label => 'Orgão'
    config.add_show_field 'tipo_conteudo', :label => 'Tipo de Conteúdo'
    config.add_show_field 'texto', :label => 'Texto'

    # "fielded" search configuration. Used by pulldown among other places.
    # For supported keys in hash, see rdoc for Blacklight::SearchFields
    #
    # Search fields will inherit the :qt solr request handler from
    # config[:default_solr_parameters], OR can specify a different one
    # with a :qt key/value. Below examples inherit, except for subject
    # that specifies the same :qt as default for our own internal
    # testing purposes.
    #
    # The :key is what will be used to identify this BL search field internally,
    # as well as in URLs -- so changing it after deployment may break bookmarked
    # urls.  A display label will be automatically calculated from the :key,
    # or can be specified manually to be different. 

    # This one uses all the defaults set by the solr request handler. Which
    # solr request handler? The one set in config[:default_solr_parameters][:qt],
    # since we aren't specifying it otherwise. 
    
    #config.add_search_field 'texto', :label => 'Texto'
    

    # Now we see how to over-ride Solr request handler defaults, in this
    # case for a BL "search field", which is really a dismax aggregate
    # of Solr search fields. 
    
    #config.add_search_field('title') do |field|
      # solr_parameters hash are sent to Solr as ordinary url query params. 
      #field.solr_parameters = { :'spellcheck.dictionary' => 'title' }

      # :solr_local_parameters will be sent using Solr LocalParams
      # syntax, as eg {! qf=$title_qf }. This is neccesary to use
      # Solr parameter de-referencing like $title_qf.
      # See: http://wiki.apache.org/solr/LocalParams
      #field.solr_local_parameters = { 
        #:qf => '$title_qf',
        #:pf => '$title_pf'
      #}
    #end
    
    #config.add_search_field('author') do |field|
      #field.solr_parameters = { :'spellcheck.dictionary' => 'author' }
      #field.solr_local_parameters = { 
        #:qf => '$author_qf',
        #:pf => '$author_pf'
      #}
    #end
    
    # Specifying a :qt only to show it's possible, and so our internal automated
    # tests can test it. In this case it's the same as 
    # config[:default_solr_parameters][:qt], so isn't actually neccesary. 
    #config.add_search_field('subject') do |field|
      #field.solr_parameters = { :'spellcheck.dictionary' => 'subject' }
      #field.qt = 'search'
      #field.solr_local_parameters = { 
        #:qf => '$subject_qf',
        #:pf => '$subject_pf'
      #}
    #end

    # "sort results by" select (pulldown)
    # label in pulldown is followed by the name of the SOLR field to sort by and
    # whether the sort is ascending or descending (it must be asc or desc
    # except in the relevancy case).
    config.add_sort_field 'score desc, data desc', :label => 'Relevância'
    config.add_sort_field 'data desc', :label => 'Data'


    # If there are more than this many search results, no spelling ("did you 
    # mean") suggestion is offered.
    config.spell_max = 5
  end

    # get search results from the solr index
    def index
      (@response, @document_list) = get_search_results
      respond_to do |format|
        format.html { }
        format.rss  { render :layout => false }
        format.atom { render :layout => false }
        hash_result = render_search_results_as_json
        hash_result[:pages][:is_first_page] = hash_result[:pages][:"first_page?"]
        hash_result[:pages][:is_last_page] = hash_result[:pages][:"last_page?"]
        hash_result[:pages].delete(:"first_page?")
        hash_result[:pages].delete(:"last_page?")
    
        format.json do
          render json: {:response => hash_result}
        end
        format.xml do
          render xml: JSON.parse(hash_result.to_json).to_xml(:root=>"response")
        end

        additional_response_formats(format)
        document_export_formats(format)
      end
    end

    def render_search_results_as_json
      {docs: @document_list, facets: search_facets_as_json, pages: pagination_info(@response)}
    end

    # get single document from the solr index
    def show
      @response, @document = get_solr_response_for_doc_id   

      respond_to do |format|
        format.html {setup_next_and_previous_documents}

        format.json { render json: {:response => @document } }
	format.xml { render xml: @document.to_xml(:root=>'response') }

        # Add all dynamically added (such as by document extensions)

app/views/catalog/_facet_limit.html.erb
<ul class="facet-values list-unstyled">
  <% paginator = facet_paginator(facet_field, display_facet)
  %>

  <%
  paginator.items.each do |item|
    next if item.value.length < 2
  -%>
   <% if item.value=='date_range' %>
     <li class="date_range"> 

	    <input type="date" class="form-control" placeholder="Data Inicial" name="date_range_begin" id="date_range_begin" value="<%=date_range[:date_range_begin]%>" />
            <input type="date" class="form-control" placeholder="Data Final" name="date_range_end" id="date_range_end" value="<%=date_range[:date_range_end]%>" />
	    <%if date_range[:date_range_begin] && date_range[:date_range_end]%>
		<%=item.hits%> documentos
		<a class="remove" href="<%=search_action_path(remove_facet_params('data','date_range',params))%>">

		    <span class="glyphicon glyphicon-remove"></span>
		    <span class="sr-only">

			[remove]

		    </span>

		</a>
	    <% end %>
	    <input type="button" value="Filtrar" style="width:100%" class="btn btn-primary btn-sm" name="date_range_button" id="date_range_button" />

	    <br />


     </li>
   <% else %>
    <li>
    <% if facet_in_params?( solr_field, item.value ) %>              
        <%= render_selected_facet_value(solr_field, item) %>              
      <% else %>              
        <%= render_facet_value(solr_field, item) %>              
    <% end -%>
    </li>
   <% end %>

  <% end %>

  <% if paginator.has_next? and params[:action] != "facet" %>
    <li class="more_facets_link"><%= link_to(t('blacklight.search.facets.more'), params.merge(:id => solr_field, :action=>"facet", :page => nil), :class => "more_facets_link") %></li>
  <% end %>

</ul>

app/views/catalog/_home_text.html.erb
<h1 class="text-center"><%= nomeEstilizado %></h1>

<%= render 'sobre' %>

app/views/catalog/_index_default.html.erb
<%# default partial to display solr document fields in catalog index view -%>
<a class="link-documento" href="<%= url_for document.id %>">
<dl class="document-metadata dl-horizontal dl-invert">
	    <dt class="blacklight-data">Data:</dt>
	    <dd class="blacklight-data"><%= formatarData(render_index_field_value document, :field => 'data') %></dd>
	    <dt class="blacklight-assunto">Assunto:</dt>
	    <dd class="blacklight-assunto"><%= render_index_field_value document, :field => 'secretaria')+' - '+(render_index_field_value document, :field => 'orgao')+' - '+(render_index_field_value document, :field => 'tipo_conteudo' %></dd>

	    <dt class="blacklight-texto">Texto:</dt>
	    <dd class="blacklight-texto"><%= textoNaoFormatado((render_index_field_value document, :field => 'texto').to_s[0..400], ['em'])%></dd>
	    <% if false %>
	    <dt>Formatos:</dt>
			<dd><%= botaoExportador("JSON","/"+document.id+".json") %> <%= botaoExportador("XML","/"+document.id+".xml") %></dd>
	    <% end %>
</dl>
</a>

app/views/catalog/_index_header_default.html.erb
     
      <% # header bar for doc items in index view -%>
      <div class="documentHeader row">
        
        <%# main title container for doc partial view 
            How many bootstrap columns need to be reserved
            for bookmarks control depends on size. 
        -%>
         <h5 class="index_title col-sm-9 col-lg-10">
         <% counter = document_counter_with_offset(document_counter) %>
         <span class="document-counter">
         <%= t('blacklight.search.documents.counter', :counter => counter) if counter %>
         </span>
        </h5>

        <% # bookmark functions for items/docs -%>
        <%= render_index_doc_actions document, :wrapping_class => "index-document-functions col-sm-3 col-lg-2" %>
      </div>
      

app/views/catalog/_search_export_formats.html.erb
<div class="search-export-formats">
  Exportar Página:
  <div class="btn-group" role="group">
    <%= botaoExportador("JSON",search_url_format("json")) %>
    <%= botaoExportador("XML",search_url_format("xml")) %>
    <%= botaoExportador("Atom",search_url_format("atom")) %>
    <%= botaoExportador("RSS",search_url_format("rss")) %>
    <a class="btn btn-primary btn-sm" href="http://devcolab.each.usp.br/do/exportadores">?</a>
  </div>
</div>

app/views/catalog/_search_form.html.erb
  <%= form_tag search_action_url, :method => :get, :class => 'search-query-form form-inline clearfix navbar-form' do %>
    <%= render_hash_as_hidden_fields(params_for_search().except(:q, :search_field, :qt, :page, :utf8)) %>

    <div class="input-group">
    <% unless search_fields.empty? %>

      <span class="input-group-addon">
        <label for="search_field" class="sr-only"><%= t('blacklight.search.form.search_field.label') %></label>
        <%= select_tag(:search_field, options_for_select(search_fields, h(params[:search_field])), :title => t('blacklight.search.form.search_field.title'), :class=>"search_field") %>
        <span class="sr-only"><%= t('blacklight.search.form.search_field.post_label') %></span>
        </span>
      <% end %>
        <label for="q" class="sr-only"><%= t('blacklight.search.form.q') %></label>
         <%= text_field_tag :q, params[:q], :placeholder => t('blacklight.search.form.q'), :class => "search_q q form-control", :id => "q", :autofocus => should_autofocus_on_search_box? %>

      <span class="input-group-btn">
        <button type="submit" class="btn btn-primary search-btn" id="search">
          <span class="submit-search-text"><%=t('blacklight.search.form.submit')%></span>
          <span class="glyphicon glyphicon-search"></span>
        </button>

		<%= link_to '?', buscaavancada_path, :class => 'btn btn-primary' %>
        </span>

      </div> 
  <% end %>

app/views/catalog/_search_header.html.erb
<%= render 'did_you_mean' %>

<%= render 'constraints' %>

<%= render 'search_export_formats' %>

<%= render 'sort_and_per_page' %>

app/views/catalog/_show_default.html.erb
<%# default partial to display solr document fields in catalog show view -%>
<dl class="dl-horizontal  dl-invert">

	    <dt class="blacklight-data">Data:</dt>
	    <dd class="blacklight-data"><%= formatarData(render_document_show_field_value document, :field => 'data') %></dd>

	    <dt class="blacklight-secretaria">Secretaria:</dt>
	    <dd class="blacklight-secretaria"><%= (render_document_show_field_value document, :field => 'secretaria') %></dd>

	    <dt class="blacklight-orgao">Orgão:</dt>
	    <dd class="blacklight-orgao"><%= (render_document_show_field_value document, :field => 'orgao') %></dd>

	    <dt class="blacklight-tipo_conteudo">Tipo de Conteúdo:</dt>
	    <dd class="blacklight-tipo_conteudo"><%= (render_document_show_field_value document, :field => 'tipo_conteudo') %></dd>

	    <dt class="blacklight-texto">Texto:</dt>
	    <dd class="blacklight-texto"><%= textoFormatado(render_document_show_field_value document, :field => 'texto') %></dd>

</dl>

app/views/catalog/_show_header_default.html.erb
<% # bookmark/folder functions -%>
<h3><%= document.id %></h3>

app/views/catalog/_show_tools.html.erb
<%-
  # Compare with render_document_functions_partial helper, and
  # _document_functions partial. BL actually has two groups
  # of document-related tools. "document functions" by default
  # contains Bookmark functionality shown on both results and
  # item view. While "document tools" contains external export type
  # functions by default only on detail.

-%>
<div class="panel panel-default show-tools">
  <div class="panel-heading">
    <%= t('blacklight.tools.title') %>
  </div>

  <div class="panel-body">
  <ul class="nav text-center">
      <li>
        <%= render_show_doc_actions @document %>
      </li>
      <% if (@document.respond_to?(:export_as_mla_citation_txt) || @document.respond_to?(:export_as_apa_citation_txt)) %>
        <li class="cite">
         <%= link_to t('blacklight.tools.cite'), citation_catalog_path(:id => @document), {:id => 'citeLink', :data => {:ajax_modal => "trigger"}} %>
        </li>
      <% end %>
      <% if @document.export_formats.keys.include?( :refworks_marc_txt ) %>
        <li class="refworks">
        <%= link_to t('blacklight.tools.refworks'), refworks_export_url(:id => @document)  %>        
        </li>
     <% end %>
     <% if @document.export_formats.keys.include?( :endnote ) %>
      <li class="endnote">
      <%= link_to t('blacklight.tools.endnote'), catalog_path(@document, :format => 'endnote') %>
      </li>
    <% end %>
    <% if false %>
    <% if @document.respond_to?( :to_email_text ) %>
      <li class="email">
	      <%= link_to '<span class="glyphicon glyphicon glyphicon-envelope"></span> '.html_safe+t('blacklight.tools.email'), email_catalog_path(:id => @document), {:id => 'emailLink', :class => 'btn btn-primary btn-xs', :data => {:ajax_modal => "trigger"}} %>
      </li>
    <%- end -%>
    <% end %>
    
    <% if respond_to? :librarian_view_catalog_path and @document.respond_to?(:to_marc) %>
      <li class="librarian_view">
        <%= link_to t('blacklight.tools.librarian_view'), librarian_view_catalog_path(@document), {:id => 'librarianLink', :data => {:ajax_modal => "trigger"}} %>
      </li>
    <% end %>
      <li>
	      <%= botaoExportador("JSON",request.fullpath+".json") %>
      </li>
      <li>
	      <%= botaoExportador("XML",request.fullpath+".xml") %>
      </li>
  </ul>
  </div>
</div>

app/views/catalog/index.html.erb
<div id="sidebar" class="col-md-4">
 <%= render 'search_sidebar' %>
</div>

<div id="content" class="col-md-8">

    <% unless has_search_parameters? %>
	    <%# if there are no input/search related params, display the "home" partial -%>
	    <%= render 'home' %>
    <% else %>

      <h2 class="sr-only top-content-title"><%= t('blacklight.search.search_results_header') %></h2>

      <% @page_title = t('blacklight.search.title', :application_name => application_name) %>


      <% content_for(:head) do -%>
        <%= render_opensearch_response_metadata %>
        <%= auto_discovery_link_tag(:rss, url_for(params.merge(:format => 'rss')), :title => t('blacklight.search.rss_feed') ) %>
        <%= auto_discovery_link_tag(:atom, url_for(params.merge(:format => 'atom')), :title => t('blacklight.search.atom_feed') ) %>
      <% end -%>


      <%= render 'search_header' %>

      <h2 class="sr-only"><%= t('blacklight.search.search_results') %></h2>

      <%- if @response.empty? %>
        <%= render "zero_results" %>
      <%- elsif render_grouped_response? %>
        <%= render_grouped_document_index %>
      <%- else %>
        <%= render_document_index %>
      <%- end %>

	    <%= render 'results_pagination' %>


    <% end %>

</div>