config/routes.rb
Rails.application.routes.draw do
  get 'baixar' => 'application#baixar'
  get 'creditos' => 'application#creditos'
  get 'privacidade' => 'application#privacidade'
  get 'buscaavancada' => 'application#buscaavancada'
  get 'exportadores' => 'application#exportadores'
  get 'duvidas' => 'application#duvidas'

  root :to => "catalog#index"
  blacklight_for :catalog
  Blacklight::Marc.add_routes(self)
  devise_for :users

  get "/:id" => "catalog#show", :constraints => {:id => /[0-9]{4}\/[0-9]{2}\/[0-9]{2}\/[0-9]+/}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Adds a few additional behaviors into the application controller 
   include Blacklight::Controller
  # Please be sure to impelement current_user and user_session. Blacklight depends on 
  # these methods in order to perform user specific actions. 

  layout 'blacklight'

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def sobre
  end

  def aaa
  end
end

app/helpers/application_helper.rb
# -*- coding: utf-8 -*-
module ApplicationHelper

  # Retorna data no formato dd/mm/yyyy
  def formatarData data
    data[8..9]+'/'+data[5..6]+'/'+data[0..3]
  end

  def search_url_format(format)
    fullpath = request.fullpath
    if fullpath.include?("catalog") && !fullpath.include?(format)
      fullpath = fullpath.gsub("catalog","catalog."+format)
    else
      fullpath = fullpath.gsub("?","catalog."+format+"?")
    end
  end

  # Substitui ((NG))texto((CL)) por <b>texto</b>
  def tagNegrito s
    s.gsub(/(\(\(NG\)\)((?!\(\(NG\)\)).)*\(\(CL\)\))/i){|m|m.gsub(/\(\(NG\)\)/i,'<b>').gsub(/\(\(CL\)\)/i,'</b>')}
  end

  # Substitui ((TITULO))titulo((TEXTO)) por <h4><b>titulo</b></h4>
  def tagTitulo s
    s.gsub(/(\(\(TITULO\)\)((?!\(\(TITULO\)\)).)*\(\(TEXTO\)\))/i){|m|m.gsub(/\(\(TITULO\)\)/i,'<h4><b>').gsub(/\(\(TEXTO\)\)/i,'</b></h4>')}
    s.gsub(/(\(\(TÍTULO\)\)((?!\(\(TÍTULO\)\)).)*\(\(TEXTO\)\))/i){|m|m.gsub(/\(\(TÍTULO\)\)/i,'<h4><b>').gsub(/\(\(TEXTO\)\)/i,'</b></h4>')}
  end

  # Substitui ((tag)) por ''
  def retirarTags s
    s.gsub(/\(\(NG\)\)/i,'').gsub(/\(\(CL\)\)/i,'').gsub(/\(\(TITULO\)\)/i,'').gsub(/\(\(TÍTULO\)\)/i,'').gsub(/\(\(TEXTO\)\)/i,'')
  end

  # Retorna texto com formatacao HTML
  def textoFormatado s
    retirarTags(tagTitulo(tagNegrito(s.gsub(/\n/, '<br />')))).html_safe
  end

  # Retorna texto sem formatacao HTML
  def textoNaoFormatado(s, tags=nil)
    # Primeiro coloca as tags HTML depois as tira.
    # Tira todas tags exceto as contidas em 'tags' - Por exemplo <em> para o Highlight das palavras buscadas.
    ActionController::Base.helpers.sanitize(textoFormatado(s).gsub(/(\<br \/\>)/,'<br /> '), :tags=>tags)
  end

  def botaoExportador(texto, link)
    ('<a class="btn btn-primary btn-sm" href="%s" role="button"><span class="glyphicon glyphicon glyphicon-download"></span> %s</a>' % [link, texto]).html_safe
  end

  def nomeEstilizado
    '<span class="font1">Diário</span> <span class="font2">Livre</span>'.html_safe
  end

  def linkQuestionario
    'http://devcolab.each.usp.br/limesurvey/index.php/191978'.html_safe
  end

  def gerarCreditosMK
    lista = [
      'Andrés M. R. Martano',
      'Rafael Santana',
      'Larissa Y. Oyadomari',
      'Gisele S. Craveiro',
      'Jorge Machado',
      'Nahema Nascimento Barra de Oliveira',
      'Emerson Marques Pedro',
      'Fabiano Angélico',
      'Gabriel Ponzetto',
      'Givanildo Andrade Lopes',
      'Fernanda Campagnucci',
      'Clarissa Carmona',
      'Alice Fernanda Dias Gonçalves',
      'Renato Mataruco Lopes',
      'José de Jesús Pérez-Al',
      'Selma Berezutchi',
      'Paulo Roberto Dutra',
      'Danilo Marasca Bertazzi',
      'Domingas Soares de Oliveira',
      'Paulo de Negreiros Spinelli',
      'Alexandre Calil',
      'Thiago Fernando dos Santos Teixeira',
    ].sort! .collect { |x| "<li>%s</li>" % x } .join "\n"
  end

end

app/views/application/_sobre.html.slim
markdown:

  # Sobre

    Este é um site experimental desenvolvido para possibilitar uma nova forma de acessar os artigos do [Diário Oficial do município de São Paulo](//www.docidadesp.imprensaoficial.com.br).
    Ele foi possível graças a uma [parceria entre a CGM e a USP](//www.prefeitura.sp.gov.br/cidade/secretarias/controladoria_geral/noticias/?p=182421), mais especificamente a [Coordenadoria de Promoção da Integridade (COPI)](//www.prefeitura.sp.gov.br/cidade/secretarias/controladoria_geral/coordenadoria_de_promocao_da_integridade/) e o [Colaboratório de Desenvolvimento e Participação (Colab)](//colab.each.usp.br).
    Há uma página específica sobre as [bases de dados dos diários oficiais usadas por este site](#{baixar_path}), elas são uma contribuição fundamental da [Secretaria Municipal de Planejamento, Orçamento e Gestão (SEMPLA)](//www.prefeitura.sp.gov.br/cidade/secretarias/planejamento/).

    É importante frisar que a versão do Diário Oficial disponibilizada aqui **NÃO POSSUI VALOR LEGAL**, ao contrário da publicada pelo site oficial.

    Aqui pode ser encontrada nossa [política de privacidade](#{privacidade_path}).

  ## Questionário

    Pelo carater experimental deste projeto, e por ele estar inserido em uma pesquisa sobre [Dados Abertos Governamentais](//pt.wikipedia.org/wiki/Dados_abertos), pedimos encarecidamente que você responda nosso [questionário](#{linkQuestionario}).


  ## Desenvolvimento

  Este site é um [software livre](//pt.wikipedia.org/wiki/Software_livre) e aqui pode ser encontrado o [repositório do código fonte](//github.com/rafaeusantana/docsolr). Seus principais desenvolvedores são **Rafael Santana** e **Andrés M. R. Martano**. Porém, ele não seria possível sem a ajuda de [tod@s que participaram deste projeto](#{creditos_path}).

  Este site se baseia principalmente em duas tecnologias (também livres): [BlackLight](//projectblacklight.org) e [Solr](//lucene.apache.org/solr).

app/views/application/baixar.html.slim
h1 Base do Diário Oficial Municipal de São Paulo (DOMSP)

p Essa página fornece links para baixar a base do DOMSP, desde 2003. Isso pode ser útil caso você queira, por exemplo, realizar algum tipo de processamento em larga escala, ou desenvolver seu próprio site de visualização dela.
p É importante ressaltar que esses arquivos podem possuir vários gigabytes de tamanho. O grande tamanho da base torna difícil que ela seja usada sem algum tipo de processamento automático por computador.


/h2 Sobre o protocolo Torrent

/p 
/  | Para permitir um acesso mais resiliente e ágil à base, optou-se por utilizar o protocolo
/  a< href="https://pt.wikipedia.org/wiki/BitTorrent" Torrent
/  | . Porém, como ainda não e possível atualizar um torrent depois de sua publicação, os arquivos referentes ao ano atual serão disponibilizados pelo método convencional (HTTP).

/p
/  | Para baixar a base via torrent é possível que você precise instalar um cliente próprio. Recomendamos um dos seguintes, por serem software livre e disponíveis para diversos sistemas operacionais:
/  ul
/    li : a href="http://deluge-torrent.org" Deluge
/    li : a href="https://www.transmissionbt.com" Transmission
/p
/  | Porém existem muitas 
/  a< href="https://en.wikipedia.org/wiki/Comparison_of_BitTorrent_clients" opções de clientes para torrent
/  | .


markdown:
  ## Formatos da base

  A base está disponibilizada em dois formatos: *bruto* e CSV. O primeiro contém todos os arquivos disponibilizados pela prefeitura, sem alteração nenhuma. Esses arquivos foram então descompactados de seus ZIPs; inferidas as datas de publicação a partir dos nomes dos ZIPs; separados os TXTs dos DOCs, PDFs etc; inferidas e padronizadas as codificações dos TXTs; inferidos os metadados a partir das retrancas; agrupados os TXTs e seus metadados em um CSV por dia de publicação; que foram finalmente compactados em um 7z.

  Resumindo: as bases em CSV não contêm todos os arquivos (contém apenas os TXTs que conseguiram ser processados), porém devem ser muito mais fáceis de serem utilizadas do que as bases *brutas*. Caso você queira utilizar todos os arquivos (como os DOCs e PDFs) ou os TXTs iniciais, terá que baixar e desbravar a base em formato *bruto*. Boa sorte. ;)

  Aqui estão os [scripts que fizemos para o tratamento da base](https://github.com/rafaeusantana/docsolr/tree/master/scripts) [[Python]](https://pt.wikipedia.org/wiki/Python), talvez ajudem.

  ##Licença

  As bases estão sob licença [Creative Commons por Atribuição 4.0](//creativecommons.org/licenses/by/4.0/deed.pt_BR).

  ## Baixar

table.table.table-hover.table-bordered
  thead
    tr
      th Descrição 
      th Data 
      th Tamanho 
      th Link
  tbody
    tr
      td Base não tratada, com todos os arquivos originais. 
      td 2003-2013 
      td ~12Gb 
      td
        s
          a href="arquivos-baixar/torrents/diarios-2003-2013.7z.torrent" torrent
        span>* ou
        a href="arquivos-baixar/zips/diarios-2003-2013.7z" target="_blank" 7z
    tr
      td Base tratada e convertida para CSVs.
      td 2003-2013 
      td ~0,7Gb 
      td
        s
          a href="arquivos-baixar/torrents/diarios-CSV-2003-2013.7z.torrent" torrent
        span>* ou
        a href="arquivos-baixar/zips/diarios-CSV-2003-2013.7z" target="_blank" 7z
    tr
      td Base tratada e convertida para CSVs. Alguns metadados corrigidos.
      td 2003-2013 
      td ---
      td EM BREVE
    tr
      td Base não tratada, com todos os arquivos originais. No caso ideal esse arquivo será atualizado diariamente.
      td 2014
      td ~2Gb
      td : a href="arquivos-baixar/zips/diarios-2014.7z" target="_blank" 7z
    tr
      td Base tratada e convertida para CSVs. No caso ideal esse arquivo será atualizado diariamente.
      td 2014
      td ~50Mb
      td : a href="arquivos-baixar/zips/diarios-CSV-2014.7z" target="_blank" 7z
    tr
      td Base não tratada, com todos os arquivos originais. No caso ideal esse arquivo será atualizado diariamente.
      td 2015
      td ~
      td : a href="arquivos-baixar/zips/diarios-2015.7z" target="_blank" 7z
    tr
      td Base tratada e convertida para CSVs. No caso ideal esse arquivo será atualizado diariamente.
      td 2015
      td ~
      td : a href="arquivos-baixar/zips/diarios-CSV-2015.7z" target="_blank" 7z

p * Os torrents parecem não estar funcionando mais...

p
  | A integridade dos arquivos baixados pode ser verificada pelas suas
  a< href="arquivos-baixar/zips/hashes.txt" hashes
  |. No caso dos torrents eles já realizam essas verificações.

div.text-center
  a href="http://lab.linkeddata.deri.ie/2010/lod-badges/"
    img.open-badge src="http://lab.linkeddata.deri.ie/2010/lod-badges/img/data-badge-4.png" alt="four star open Web data"

  a href="https://creativecommons.org/licenses/by/4.0/deed.pt_BR"
    img.open-badge src="https://licensebuttons.net/l/by/4.0/88x31.png" alt="creative commons por atribuição"

app/views/application/buscaavancada.slim
h1 Busca Avançada

p Por padrão, quando se digita algo no formulário de busca acima e aperta-se o botão "Buscar", a busca é feita no campo <strong>texto</strong> de cada artigo dos Diários. Porém, utilizando-se uma sintaxe especial, é possivel que a busca seja feita em outros campos dos artigos. Isso permite, por exemplo, buscar artigos publicados por um determinado órgão. Para fazer uma busca em outros campos que não sejam o texto principal do artigo, deve-se utilizar a seguinte sintaxe:

.well campo1:valor1 campo2:valor2 campo3:valor3 ...

p Os campos podem ser repetidos para colocar mais de uma restrição.

h2 Campos de busca

p Os campos que podem ser usados na busca são:

ul
  li : strong secretaria
  li : strong orgao
  li : strong tipo_conteudo
  li : strong texto
  li : strong data

h2 Exemplos

p 
  | Para procurar por artigos que contenham a palavra "educação" no campo 
  strong secretaria 
  | "diretoria" no campo 
  strong orgao 
  | e "cronograma" no 
  strong texto 
  | do próprio artigo, pode-se buscar pela seguinte frase:

.well
  strong secretaria:
  | educação 
  strong orgao:
  | diretoria 
  strong texto:
  | cronograma

p
  | De maneira análoga, para procurar por artigos que contenham as palavras "verde e meio ambiente" no campo 
  strong secretaria
  | , "editais" no campo 
  strong tipo_conteudo 
  | e "aprovação" no campo 
  strong texto
  | , pode-se buscar pela frase abaixo:

.well
  strong secretaria:
  | "verde e meio ambiente" 
  strong tipo_conteudo:
  | editais aprovação

p 
  | Repare que não foi especificado o campo para a palavra "aprovação". Nesse caso, o campo padrão de busca é o campo 
  strong texto
  | .

p
  | Por fim, para se procurar por artigos publicados entre 31/10/2012 e 31/12/2012, pode-se utilizar a frase seguinte:

.well
  strong data:
  | [2012-10-31T00:00:00.000Z TO 2012-12-31T00:00:00.000Z]

p 

app/views/application/creditos.html.slim
markdown:

  # Créditos

  É difícil citar todas as pessoas que contribuíram com este projeto, mas tentaremos citar algumas. Em ordem alfabética:

ul
  ==gerarCreditosMK

app/views/application/duvidas.slim
h1 Dúvidas?

h3 id="avisos" Como receber avisos sobre novos artigos contendo determinadas palavras chave?

markdown:

    - Fazer a busca com todas as [palavras chave](/do/buscaavancada) e configurações que quiser
    - Ordenar por data (para a primeira página sempre mostrar os resultados mais recentes)
    - Colocar o máximo de resultados por página (100)
    - Copiar o [link RSS ou Atom](/do/exportadores) e colocar no cliente escolhido. Se for usar o próprio navegador deve ser só clicar.

    **Aviso:** é possível que se aparecerem mais resultados do que couberem em uma página, os resultados das páginas sequintes não serão enviados via RSS ou Atom... Por isso a recomendação de colocar o máximo de resultados por página, reduzindo essa chance.

app/views/application/exportadores.slim
markdown:

    # Exportadores

    Exportadores são maneiras de extrair os dados disponíveis aqui para formatos mais fáceis de serem utilizá-los em outros sistemas ou programas. Quando você faz uma busca nesse site, terá no canto superior direito os botões para extrair a busca feita nos seguintes formatos:

    - [JSON](https://pt.wikipedia.org/wiki/JSON)
    - [XML](ttps://pt.wikipedia.org/wiki/XML)
    - [Atom](ttps://pt.wikipedia.org/wiki/Atom)
    - [RSS](ttps://pt.wikipedia.org/wiki/RSS)

    Os dois primeiros geralmente serão mais úteis para pessoas que queiram desenvolver sites ou programas importando automaticamente os dados daqui.

    Já os dois últimos são "agregadores de notícias". Formatos próprios para quem quer receber avisos quando surgirem mais artigos em uma determinada busca.
    A maioria dos navegadores consegue lidar com esses formatos simplesmente clicando no link correspondente.
    O programas de leitura de e-mail também costumam coseguir usar esses links.
    Além disso, esse protocolos são suportados por uma infinidade de programas e sites.
    Aqui há uma lista de [alguns programas para acompanhar RSS ou Atom](https://en.wikipedia.org/wiki/Comparison_of_feed_aggregators).
    Atualmente os resultados retornados por Atom estão com mais informações sobre os artigos encontrados do que os via RSS. Escolha o que preferir. De qualquer forma, você deverá poder clicar nos links para os artigos e lê-los na íntegra.

app/views/application/privacidade.html.slim
markdown:

  # Política de Privacidade

  ## Cookies

  Este site utiliza cookies com três propósitos:

  - Saber quando você fechou a barra anunciando sobre o questionário, para que ela não apareça de novo.
  - Login, caso você crie um usuário para ter acesso às funcionalidades personalizadas.
  - Estatísticas de uso do site.

  ## Estatísticas de Uso

    A grande maioria dos site utiliza algum tipo de registro de acesso para analisar coisas como: quantas pessoas acessaram o site, quais as páginas mais vistas, quais os navegadores/dispositivos mais utilizados, etc.
    Esses dados podem permitir que o site seja aprimorado de acordo com as necessidades encontradas.
    Porém, a coleta desses dados pode representar um problema de privacidade, especialmente quando a grande maioria dos sites utiliza uma mesma ferramenta que envia todos os dados para uma mesma empresa, [Google Analytics](https://en.wikipedia.org/wiki/Google_Analytics#Privacy_issues).

    Buscando contornar tal questão, este site utiliza uma ferramenta livre de análise de acesso, a [Piwik](http://piwik.org/), que, hospedada em nosso próprio servidor, não requer o envio dos dados à terceiros.

app/views/application/sobre.html.erb
<h2>Sobre</h2>

http://projectblacklight.org/
https://github.com/rafaeusantana/docsolr